baseURL = 'http://awujournal.cn/'
languageCode = 'zh-CN'
title = '你好我是Kousei'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'zh-CN'
[languages]
  [languages.zh-CN]
    languageName = "简体中文"
    weight = 1
    hasCJKLanguage = true

  

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = [ "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
